### ISSUE TITLE
Thumbnail not being saved when using custom image for new Asset Pack

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#692]

**Comment by nicosantangelo** [comment]
The problem is that when `const url = URL.createObjectURL(file)` runs on `AssetPackEditor/AssetPackEditor.tsx` as a result of adding a custom image to the asset pack the return value is something like `blob:https://builder.decentraland.zone/cbfdad6f-28c0-4a9a-8e66-8dff8f727c64`

The thing is that, when the asset pack is submitted, the `dataURLToBlob` function tries to transform that to a blob and fails:
`dataURLToBlob('blob:https://builder.decentraland.zone/cbfdad6f-28c0-4a9a-8e66-8dff8f727c64') // => null`

that happens on `builder/src/lib/api/builder.ts#saveAssetPackThumbnail`
